export const countries: ISelectOption[] = [
  { label: "Afghanistan", value: "AF", src: "https://flagcdn.com/af.svg" },
  { label: "land Islands", value: "AX", src: "https://flagcdn.com/ax.svg" },
  { label: "Albania", value: "AL", src: "https://flagcdn.com/al.svg" },
  { label: "Algeria", value: "DZ", src: "https://flagcdn.com/dz.svg" },
  { label: "American Samoa", value: "AS", src: "https://flagcdn.com/as.svg" },
  { label: "AndorrA", value: "AD", src: "https://flagcdn.com/ad.svg" },
  { label: "Angola", value: "AO", src: "https://flagcdn.com/ao.svg" },
  { label: "Anguilla", value: "AI", src: "https://flagcdn.com/ai.svg" },
  { label: "Antarctica", value: "AQ", src: "https://flagcdn.com/aq.svg" },
  { label: "Antigua and Barbuda", value: "AG", src: "https://flagcdn.com/ag.svg" },
  { label: "Argentina", value: "AR", src: "https://flagcdn.com/ar.svg" },
  { label: "Armenia", value: "AM", src: "https://flagcdn.com/am.svg" },
  { label: "Aruba", value: "AW", src: "https://flagcdn.com/aw.svg" },
  { label: "Australia", value: "AU", src: "https://flagcdn.com/au.svg" },
  { label: "Austria", value: "AT", src: "https://flagcdn.com/at.svg" },
  { label: "Azerbaijan", value: "AZ", src: "https://flagcdn.com/az.svg" },
  { label: "Bahamas", value: "BS", src: "https://flagcdn.com/bs.svg" },
  { label: "Bahrain", value: "BH", src: "https://flagcdn.com/bh.svg" },
  { label: "Bangladesh", value: "BD", src: "https://flagcdn.com/bd.svg" },
  { label: "Barbados", value: "BB", src: "https://flagcdn.com/bb.svg" },
  { label: "Belarus", value: "BY", src: "https://flagcdn.com/by.svg" },
  { label: "Belgium", value: "BE", src: "https://flagcdn.com/be.svg" },
  { label: "Belize", value: "BZ", src: "https://flagcdn.com/bz.svg" },
  { label: "Benin", value: "BJ", src: "https://flagcdn.com/bj.svg" },
  { label: "Bermuda", value: "BM", src: "https://flagcdn.com/bm.svg" },
  { label: "Bhutan", value: "BT", src: "https://flagcdn.com/bt.svg" },
  { label: "Bolivia", value: "BO", src: "https://flagcdn.com/bo.svg" },
  { label: "Bosnia and Herzegovina", value: "BA", src: "https://flagcdn.com/ba.svg" },
  { label: "Botswana", value: "BW", src: "https://flagcdn.com/bw.svg" },
  { label: "Bouvet Island", value: "BV", src: "https://flagcdn.com/bv.svg" },
  { label: "Brazil", value: "BR", src: "https://flagcdn.com/br.svg" },
  { label: "British Indian Ocean Territory", value: "IO", src: "https://flagcdn.com/io.svg" },
  { label: "Brunei Darussalam", value: "BN", src: "https://flagcdn.com/bn.svg" },
  { label: "Bulgaria", value: "BG", src: "https://flagcdn.com/bg.svg" },
  { label: "Burkina Faso", value: "BF", src: "https://flagcdn.com/bf.svg" },
  { label: "Burundi", value: "BI", src: "https://flagcdn.com/bi.svg" },
  { label: "Cambodia", value: "KH", src: "https://flagcdn.com/kh.svg" },
  { label: "Cameroon", value: "CM", src: "https://flagcdn.com/cm.svg" },
  { label: "Canada", value: "CA", src: "https://flagcdn.com/ca.svg" },
  { label: "Cape Verde", value: "CV", src: "https://flagcdn.com/cv.svg" },
  { label: "Cayman Islands", value: "KY", src: "https://flagcdn.com/ky.svg" },
  { label: "Central African Republic", value: "CF", src: "https://flagcdn.com/cf.svg" },
  { label: "Chad", value: "TD", src: "https://flagcdn.com/td.svg" },
  { label: "Chile", value: "CL", src: "https://flagcdn.com/cl.svg" },
  { label: "China", value: "CN", src: "https://flagcdn.com/cn.svg" },
  { label: "Christmas Island", value: "CX", src: "https://flagcdn.com/cx.svg" },
  { label: "Cocos (Keeling) Islands", value: "CC", src: "https://flagcdn.com/cc.svg" },
  { label: "Colombia", value: "CO", src: "https://flagcdn.com/co.svg" },
  { label: "Comoros", value: "KM", src: "https://flagcdn.com/km.svg" },
  { label: "Congo", value: "CG", src: "https://flagcdn.com/cg.svg" },
  { label: "Congo, The Democratic Republic of the", value: "CD", src: "https://flagcdn.com/cd.svg" },
  { label: "Cook Islands", value: "CK", src: "https://flagcdn.com/ck.svg" },
  { label: "Costa Rica", value: "CR", src: "https://flagcdn.com/cr.svg" },
  { label: "Cote D'Ivoire", value: "CI", src: "https://flagcdn.com/ci.svg" },
  { label: "Croatia", value: "HR", src: "https://flagcdn.com/hr.svg" },
  { label: "Cuba", value: "CU", src: "https://flagcdn.com/cu.svg" },
  { label: "Cyprus", value: "CY", src: "https://flagcdn.com/cy.svg" },
  { label: "Czech Republic", value: "CZ", src: "https://flagcdn.com/cz.svg" },
  { label: "Denmark", value: "DK", src: "https://flagcdn.com/dk.svg" },
  { label: "Djibouti", value: "DJ", src: "https://flagcdn.com/dj.svg" },
  { label: "Dominica", value: "DM", src: "https://flagcdn.com/dm.svg" },
  { label: "Dominican Republic", value: "DO", src: "https://flagcdn.com/do.svg" },
  { label: "Ecuador", value: "EC", src: "https://flagcdn.com/ec.svg" },
  { label: "Egypt", value: "EG", src: "https://flagcdn.com/eg.svg" },
  { label: "El Salvador", value: "SV", src: "https://flagcdn.com/sv.svg" },
  { label: "Equatorial Guinea", value: "GQ", src: "https://flagcdn.com/gq.svg" },
  { label: "Eritrea", value: "ER", src: "https://flagcdn.com/er.svg" },
  { label: "Estonia", value: "EE", src: "https://flagcdn.com/ee.svg" },
  { label: "Ethiopia", value: "ET", src: "https://flagcdn.com/et.svg" },
  { label: "Falkland Islands (Malvinas)", value: "FK", src: "https://flagcdn.com/fk.svg" },
  { label: "Faroe Islands", value: "FO", src: "https://flagcdn.com/fo.svg" },
  { label: "Fiji", value: "FJ", src: "https://flagcdn.com/fj.svg" },
  { label: "Finland", value: "FI", src: "https://flagcdn.com/fi.svg" },
  { label: "France", value: "FR", src: "https://flagcdn.com/fr.svg" },
  { label: "French Guiana", value: "GF", src: "https://flagcdn.com/gf.svg" },
  { label: "French Polynesia", value: "PF", src: "https://flagcdn.com/pf.svg" },
  { label: "French Southern Territories", value: "TF", src: "https://flagcdn.com/tf.svg" },
  { label: "Gabon", value: "GA", src: "https://flagcdn.com/ga.svg" },
  { label: "Gambia", value: "GM", src: "https://flagcdn.com/gm.svg" },
  { label: "Georgia", value: "GE", src: "https://flagcdn.com/ge.svg" },
  { label: "Germany", value: "DE", src: "https://flagcdn.com/de.svg" },
  { label: "Ghana", value: "GH", src: "https://flagcdn.com/gh.svg" },
  { label: "Gibraltar", value: "GI", src: "https://flagcdn.com/gi.svg" },
  { label: "Greece", value: "GR", src: "https://flagcdn.com/gr.svg" },
  { label: "Greenland", value: "GL", src: "https://flagcdn.com/gl.svg" },
  { label: "Grenada", value: "GD", src: "https://flagcdn.com/gd.svg" },
  { label: "Guadeloupe", value: "GP", src: "https://flagcdn.com/gp.svg" },
  { label: "Guam", value: "GU", src: "https://flagcdn.com/gu.svg" },
  { label: "Guatemala", value: "GT", src: "https://flagcdn.com/gt.svg" },
  { label: "Guernsey", value: "GG", src: "https://flagcdn.com/gg.svg" },
  { label: "Guinea", value: "GN", src: "https://flagcdn.com/gn.svg" },
  { label: "Guinea-Bissau", value: "GW", src: "https://flagcdn.com/gw.svg" },
  { label: "Guyana", value: "GY", src: "https://flagcdn.com/gy.svg" },
  { label: "Haiti", value: "HT", src: "https://flagcdn.com/ht.svg" },
  { label: "Heard Island and Mcdonald Islands", value: "HM", src: "https://flagcdn.com/hm.svg" },
  { label: "Holy See (Vatican City State)", value: "VA", src: "https://flagcdn.com/va.svg" },
  { label: "Honduras", value: "HN", src: "https://flagcdn.com/hn.svg" },
  { label: "Hong Kong", value: "HK", src: "https://flagcdn.com/hk.svg" },
  { label: "Hungary", value: "HU", src: "https://flagcdn.com/hu.svg" },
  { label: "Iceland", value: "IS", src: "https://flagcdn.com/is.svg" },
  { label: "India", value: "IN", src: "https://flagcdn.com/in.svg" },
  { label: "Indonesia", value: "ID", src: "https://flagcdn.com/id.svg" },
  { label: "Iran, Islamic Republic Of", value: "IR", src: "https://flagcdn.com/ir.svg" },
  { label: "Iraq", value: "IQ", src: "https://flagcdn.com/iq.svg" },
  { label: "Ireland", value: "IE", src: "https://flagcdn.com/ie.svg" },
  { label: "Isle of Man", value: "IM", src: "https://flagcdn.com/im.svg" },
  { label: "Israel", value: "IL", src: "https://flagcdn.com/il.svg" },
  { label: "Italy", value: "IT", src: "https://flagcdn.com/it.svg" },
  { label: "Jamaica", value: "JM", src: "https://flagcdn.com/jm.svg" },
  { label: "Japan", value: "JP", src: "https://flagcdn.com/jp.svg" },
  { label: "Jersey", value: "JE", src: "https://flagcdn.com/je.svg" },
  { label: "Jordan", value: "JO", src: "https://flagcdn.com/jo.svg" },
  { label: "Kazakhstan", value: "KZ", src: "https://flagcdn.com/kz.svg" },
  { label: "Kenya", value: "KE", src: "https://flagcdn.com/ke.svg" },
  { label: "Kiribati", value: "KI", src: "https://flagcdn.com/ki.svg" },
  { label: 'Korea, Democratic People"S Republic of', value: "KP", src: "https://flagcdn.com/kp.svg" },
  { label: "Korea, Republic of", value: "KR", src: "https://flagcdn.com/kr.svg" },
  { label: "Kuwait", value: "KW", src: "https://flagcdn.com/kw.svg" },
  { label: "Kyrgyzstan", value: "KG", src: "https://flagcdn.com/kg.svg" },
  { label: 'Lao People"S Democratic Republic', value: "LA", src: "https://flagcdn.com/la.svg" },
  { label: "Latvia", value: "LV", src: "https://flagcdn.com/lv.svg" },
  { label: "Lebanon", value: "LB", src: "https://flagcdn.com/lb.svg" },
  { label: "Lesotho", value: "LS", src: "https://flagcdn.com/ls.svg" },
  { label: "Liberia", value: "LR", src: "https://flagcdn.com/lr.svg" },
  { label: "Libyan Arab Jamahiriya", value: "LY", src: "https://flagcdn.com/ly.svg" },
  { label: "Liechtenstein", value: "LI", src: "https://flagcdn.com/li.svg" },
  { label: "Lithuania", value: "LT", src: "https://flagcdn.com/lt.svg" },
  { label: "Luxembourg", value: "LU", src: "https://flagcdn.com/lu.svg" },
  { label: "Macao", value: "MO", src: "https://flagcdn.com/mo.svg" },
  { label: "Macedonia, The Former Yugoslav Republic of", value: "MK", src: "https://flagcdn.com/mk.svg" },
  { label: "Madagascar", value: "MG", src: "https://flagcdn.com/mg.svg" },
  { label: "Malawi", value: "MW", src: "https://flagcdn.com/mw.svg" },
  { label: "Malaysia", value: "MY", src: "https://flagcdn.com/my.svg" },
  { label: "Maldives", value: "MV", src: "https://flagcdn.com/mv.svg" },
  { label: "Mali", value: "ML", src: "https://flagcdn.com/ml.svg" },
  { label: "Malta", value: "MT", src: "https://flagcdn.com/mt.svg" },
  { label: "Marshall Islands", value: "MH", src: "https://flagcdn.com/mh.svg" },
  { label: "Martinique", value: "MQ", src: "https://flagcdn.com/mq.svg" },
  { label: "Mauritania", value: "MR", src: "https://flagcdn.com/mr.svg" },
  { label: "Mauritius", value: "MU", src: "https://flagcdn.com/mu.svg" },
  { label: "Mayotte", value: "YT", src: "https://flagcdn.com/yt.svg" },
  { label: "Mexico", value: "MX", src: "https://flagcdn.com/mx.svg" },
  { label: "Micronesia, Federated States of", value: "FM", src: "https://flagcdn.com/fm.svg" },
  { label: "Moldova, Republic of", value: "MD", src: "https://flagcdn.com/md.svg" },
  { label: "Monaco", value: "MC", src: "https://flagcdn.com/mc.svg" },
  { label: "Mongolia", value: "MN", src: "https://flagcdn.com/mn.svg" },
  { label: "Montenegro", value: "ME", src: "https://flagcdn.com/me.svg" },
  { label: "Montserrat", value: "MS", src: "https://flagcdn.com/ms.svg" },
  { label: "Morocco", value: "MA", src: "https://flagcdn.com/ma.svg" },
  { label: "Mozambique", value: "MZ", src: "https://flagcdn.com/mz.svg" },
  { label: "Myanmar", value: "MM", src: "https://flagcdn.com/mm.svg" },
  { label: "Namibia", value: "NA", src: "https://flagcdn.com/na.svg" },
  { label: "Nauru", value: "NR", src: "https://flagcdn.com/nr.svg" },
  { label: "Nepal", value: "NP", src: "https://flagcdn.com/np.svg" },
  { label: "Netherlands", value: "NL", src: "https://flagcdn.com/nl.svg" },
  { label: "Netherlands Antilles", value: "AN", src: "https://flagcdn.com/an.svg" },
  { label: "New Caledonia", value: "NC", src: "https://flagcdn.com/nc.svg" },
  { label: "New Zealand", value: "NZ", src: "https://flagcdn.com/nz.svg" },
  { label: "Nicaragua", value: "NI", src: "https://flagcdn.com/ni.svg" },
  { label: "Niger", value: "NE", src: "https://flagcdn.com/ne.svg" },
  { label: "Nigeria", value: "NG", src: "https://flagcdn.com/ng.svg" },
  { label: "Niue", value: "NU", src: "https://flagcdn.com/nu.svg" },
  { label: "Norfolk Island", value: "NF", src: "https://flagcdn.com/nf.svg" },
  { label: "Northern Mariana Islands", value: "MP", src: "https://flagcdn.com/mp.svg" },
  { label: "Norway", value: "NO", src: "https://flagcdn.com/no.svg" },
  { label: "Oman", value: "OM", src: "https://flagcdn.com/om.svg" },
  { label: "Pakistan", value: "PK", src: "https://flagcdn.com/pk.svg" },
  { label: "Palau", value: "PW", src: "https://flagcdn.com/pw.svg" },
  { label: "Palestinian Territory, Occupied", value: "PS", src: "https://flagcdn.com/ps.svg" },
  { label: "Panama", value: "PA", src: "https://flagcdn.com/pa.svg" },
  { label: "Papua New Guinea", value: "PG", src: "https://flagcdn.com/pg.svg" },
  { label: "Paraguay", value: "PY", src: "https://flagcdn.com/py.svg" },
  { label: "Peru", value: "PE", src: "https://flagcdn.com/pe.svg" },
  { label: "Philippines", value: "PH", src: "https://flagcdn.com/ph.svg" },
  { label: "Pitcairn", value: "PN", src: "https://flagcdn.com/pn.svg" },
  { label: "Poland", value: "PL", src: "https://flagcdn.com/pl.svg" },
  { label: "Portugal", value: "PT", src: "https://flagcdn.com/pt.svg" },
  { label: "Puerto Rico", value: "PR", src: "https://flagcdn.com/pr.svg" },
  { label: "Qatar", value: "QA", src: "https://flagcdn.com/qa.svg" },
  { label: "Reunion", value: "RE", src: "https://flagcdn.com/re.svg" },
  { label: "Romania", value: "RO", src: "https://flagcdn.com/ro.svg" },
  { label: "Russian Federation", value: "RU", src: "https://flagcdn.com/ru.svg" },
  { label: "RWANDA", value: "RW", src: "https://flagcdn.com/rw.svg" },
  { label: "Saint Helena", value: "SH", src: "https://flagcdn.com/sh.svg" },
  { label: "Saint Kitts and Nevis", value: "KN", src: "https://flagcdn.com/kn.svg" },
  { label: "Saint Lucia", value: "LC", src: "https://flagcdn.com/lc.svg" },
  { label: "Saint Pierre and Miquelon", value: "PM", src: "https://flagcdn.com/pm.svg" },
  { label: "Saint Vincent and the Grenadines", value: "VC", src: "https://flagcdn.com/vc.svg" },
  { label: "Samoa", value: "WS", src: "https://flagcdn.com/ws.svg" },
  { label: "San Marino", value: "SM", src: "https://flagcdn.com/sm.svg" },
  { label: "Sao Tome and Principe", value: "ST", src: "https://flagcdn.com/st.svg" },
  { label: "Saudi Arabia", value: "SA", src: "https://flagcdn.com/sa.svg" },
  { label: "Senegal", value: "SN", src: "https://flagcdn.com/sn.svg" },
  { label: "Serbia", value: "RS", src: "https://flagcdn.com/rs.svg" },
  { label: "Seychelles", value: "SC", src: "https://flagcdn.com/sc.svg" },
  { label: "Sierra Leone", value: "SL", src: "https://flagcdn.com/sl.svg" },
  { label: "Singapore", value: "SG", src: "https://flagcdn.com/sg.svg" },
  { label: "Slovakia", value: "SK", src: "https://flagcdn.com/sk.svg" },
  { label: "Slovenia", value: "SI", src: "https://flagcdn.com/si.svg" },
  { label: "Solomon Islands", value: "SB", src: "https://flagcdn.com/sb.svg" },
  { label: "Somalia", value: "SO", src: "https://flagcdn.com/so.svg" },
  { label: "South Africa", value: "ZA", src: "https://flagcdn.com/za.svg" },
  { label: "South Georgia and the South Sandwich Islands", value: "GS", src: "https://flagcdn.com/gs.svg" },
  { label: "Spain", value: "ES", src: "https://flagcdn.com/es.svg" },
  { label: "Sri Lanka", value: "LK", src: "https://flagcdn.com/lk.svg" },
  { label: "Sudan", value: "SD", src: "https://flagcdn.com/sd.svg" },
  { label: "Suriname", value: "SR", src: "https://flagcdn.com/sr.svg" },
  { label: "Svalbard and Jan Mayen", value: "SJ", src: "https://flagcdn.com/sj.svg" },
  { label: "Swaziland", value: "SZ", src: "https://flagcdn.com/sz.svg" },
  { label: "Sweden", value: "SE", src: "https://flagcdn.com/se.svg" },
  { label: "Switzerland", value: "CH", src: "https://flagcdn.com/ch.svg" },
  { label: "Syrian Arab Republic", value: "SY", src: "https://flagcdn.com/sy.svg" },
  { label: "Taiwan, Province of China", value: "TW", src: "https://flagcdn.com/tw.svg" },
  { label: "Tajikistan", value: "TJ", src: "https://flagcdn.com/tj.svg" },
  { label: "Tanzania", value: "TZ", src: "https://flagcdn.com/tz.svg" },
  { label: "Thailand", value: "TH", src: "https://flagcdn.com/th.svg" },
  { label: "Timor-Leste", value: "TL", src: "https://flagcdn.com/tl.svg" },
  { label: "Togo", value: "TG", src: "https://flagcdn.com/tg.svg" },
  { label: "Tokelau", value: "TK", src: "https://flagcdn.com/tk.svg" },
  { label: "Tonga", value: "TO", src: "https://flagcdn.com/to.svg" },
  { label: "Trinidad and Tobago", value: "TT", src: "https://flagcdn.com/tt.svg" },
  { label: "Tunisia", value: "TN", src: "https://flagcdn.com/tn.svg" },
  { label: "Turkey", value: "TR", src: "https://flagcdn.com/tr.svg" },
  { label: "Turkmenistan", value: "TM", src: "https://flagcdn.com/tm.svg" },
  { label: "Turks and Caicos Islands", value: "TC", src: "https://flagcdn.com/tc.svg" },
  { label: "Tuvalu", value: "TV", src: "https://flagcdn.com/tv.svg" },
  { label: "Uganda", value: "UG", src: "https://flagcdn.com/ug.svg" },
  { label: "Ukraine", value: "UA", src: "https://flagcdn.com/ua.svg" },
  { label: "United Arab Emirates", value: "AE", src: "https://flagcdn.com/ae.svg" },
  { label: "United Kingdom", value: "GB", src: "https://flagcdn.com/gb.svg" },
  { label: "United States", value: "US", src: "https://flagcdn.com/us.svg" },
  { label: "United States Minor Outlying Islands", value: "UM", src: "https://flagcdn.com/um.svg" },
  { label: "Uruguay", value: "UY", src: "https://flagcdn.com/uy.svg" },
  { label: "Uzbekistan", value: "UZ", src: "https://flagcdn.com/uz.svg" },
  { label: "Vanuatu", value: "VU", src: "https://flagcdn.com/vu.svg" },
  { label: "Venezuela", value: "VE", src: "https://flagcdn.com/ve.svg" },
  { label: "Viet Nam", value: "VN", src: "https://flagcdn.com/vn.svg" },
  { label: "Virgin Islands, British", value: "VG", src: "https://flagcdn.com/vg.svg" },
  { label: "Virgin Islands, U.S.", value: "VI", src: "https://flagcdn.com/vi.svg" },
  { label: "Wallis and Futuna", value: "WF", src: "https://flagcdn.com/wf.svg" },
  { label: "Western Sahara", value: "EH", src: "https://flagcdn.com/eh.svg" },
  { label: "Yemen", value: "YE", src: "https://flagcdn.com/ye.svg" },
  { label: "Zambia", value: "ZM", src: "https://flagcdn.com/zm.svg" },
  { label: "Zimbabwe", value: "ZW", src: "https://flagcdn.com/zw.svg" },
];
