export const phoneCodes: ISelectOption[] = [
  { label: "Afghanistan (+93)", value: "+93", src: "https://flagcdn.com/af.svg" },
  { label: "Åland Islands (+358)", value: "+358", src: "https://flagcdn.com/ax.svg" },
  { label: "Albania (+355)", value: "+355", src: "https://flagcdn.com/al.svg" },
  { label: "Algeria (+213)", value: "+213", src: "https://flagcdn.com/dz.svg" },
  { label: "American Samoa (+1-684)", value: "+1-684", src: "https://flagcdn.com/as.svg" },
  { label: "Andorra (+376)", value: "+376", src: "https://flagcdn.com/ad.svg" },
  { label: "Angola (+244)", value: "+244", src: "https://flagcdn.com/ao.svg" },
  { label: "Anguilla (+1-264)", value: "+1-264", src: "https://flagcdn.com/ai.svg" },
  { label: "Antarctica (+672)", value: "+672", src: "https://flagcdn.com/aq.svg" },
  { label: "Antigua and Barbuda (+1-268)", value: "+1-268", src: "https://flagcdn.com/ag.svg" },
  { label: "Argentina (+54)", value: "+54", src: "https://flagcdn.com/ar.svg" },
  { label: "Armenia (+374)", value: "+374", src: "https://flagcdn.com/am.svg" },
  { label: "Aruba (+297)", value: "+297", src: "https://flagcdn.com/aw.svg" },
  { label: "Australia (+61)", value: "+61", src: "https://flagcdn.com/au.svg" },
  { label: "Austria (+43)", value: "+43", src: "https://flagcdn.com/at.svg" },
  { label: "Azerbaijan (+994)", value: "+994", src: "https://flagcdn.com/az.svg" },
  { label: "Bahamas (+1-242)", value: "+1-242", src: "https://flagcdn.com/bs.svg" },
  { label: "Bahrain (+973)", value: "+973", src: "https://flagcdn.com/bh.svg" },
  { label: "Bangladesh (+880)", value: "+880", src: "https://flagcdn.com/bd.svg" },
  { label: "Barbados (+1-246)", value: "+1-246", src: "https://flagcdn.com/bb.svg" },
  { label: "Belarus (+375)", value: "+375", src: "https://flagcdn.com/by.svg" },
  { label: "Belgium (+32)", value: "+32", src: "https://flagcdn.com/be.svg" },
  { label: "Belize (+501)", value: "+501", src: "https://flagcdn.com/bz.svg" },
  { label: "Benin (+229)", value: "+229", src: "https://flagcdn.com/bj.svg" },
  { label: "Bermuda (+1-441)", value: "+1-441", src: "https://flagcdn.com/bm.svg" },
  { label: "Bhutan (+975)", value: "+975", src: "https://flagcdn.com/bt.svg" },
  { label: "Bolivia (+591)", value: "+591", src: "https://flagcdn.com/bo.svg" },
  { label: "Bosnia and Herzegovina (+387)", value: "+387", src: "https://flagcdn.com/ba.svg" },
  { label: "Botswana (+267)", value: "+267", src: "https://flagcdn.com/bw.svg" },
  { label: "Bouvet Island (+47)", value: "+47", src: "https://flagcdn.com/bv.svg" },
  { label: "Brazil (+55)", value: "+55", src: "https://flagcdn.com/br.svg" },
  { label: "British Indian Ocean Territory (+246)", value: "+246", src: "https://flagcdn.com/io.svg" },
  { label: "Brunei Darussalam (+673)", value: "+673", src: "https://flagcdn.com/bn.svg" },
  { label: "Bulgaria (+359)", value: "+359", src: "https://flagcdn.com/bg.svg" },
  { label: "Burkina Faso (+226)", value: "+226", src: "https://flagcdn.com/bf.svg" },
  { label: "Burundi (+257)", value: "+257", src: "https://flagcdn.com/bi.svg" },
  { label: "Cambodia (+855)", value: "+855", src: "https://flagcdn.com/kh.svg" },
  { label: "Cameroon (+237)", value: "+237", src: "https://flagcdn.com/cm.svg" },
  { label: "Canada (+1)", value: "+1", src: "https://flagcdn.com/ca.svg" },
  { label: "Cape Verde (+238)", value: "+238", src: "https://flagcdn.com/cv.svg" },
  { label: "Cayman Islands (+1-345)", value: "+1-345", src: "https://flagcdn.com/ky.svg" },
  { label: "Central African Republic (+236)", value: "+236", src: "https://flagcdn.com/cf.svg" },
  { label: "Chad (+235)", value: "+235", src: "https://flagcdn.com/td.svg" },
  { label: "Chile (+56)", value: "+56", src: "https://flagcdn.com/cl.svg" },
  { label: "China (+86)", value: "+86", src: "https://flagcdn.com/cn.svg" },
  { label: "Christmas Island (+61)", value: "+61", src: "https://flagcdn.com/cx.svg" },
  { label: "Cocos (Keeling) Islands (+61)", value: "+61", src: "https://flagcdn.com/cc.svg" },
  { label: "Colombia (+57)", value: "+57", src: "https://flagcdn.com/co.svg" },
  { label: "Comoros (+269)", value: "+269", src: "https://flagcdn.com/km.svg" },
  { label: "Congo (+242)", value: "+242", src: "https://flagcdn.com/cg.svg" },
  { label: "Congo, The Democratic Republic of the (+243)", value: "+243", src: "https://flagcdn.com/cd.svg" },
  { label: "Cook Islands (+682)", value: "+682", src: "https://flagcdn.com/ck.svg" },
  { label: "Costa Rica (+506)", value: "+506", src: "https://flagcdn.com/cr.svg" },
  { label: "Côte d'Ivoire (+225)", value: "+225", src: "https://flagcdn.com/ci.svg" },
  { label: "Croatia (+385)", value: "+385", src: "https://flagcdn.com/hr.svg" },
  { label: "Cuba (+53)", value: "+53", src: "https://flagcdn.com/cu.svg" },
  { label: "Cyprus (+357)", value: "+357", src: "https://flagcdn.com/cy.svg" },
  { label: "Czech Republic (+420)", value: "+420", src: "https://flagcdn.com/cz.svg" },
  { label: "Denmark (+45)", value: "+45", src: "https://flagcdn.com/dk.svg" },
  { label: "Djibouti (+253)", value: "+253", src: "https://flagcdn.com/dj.svg" },
  { label: "Dominica (+1-767)", value: "+1-767", src: "https://flagcdn.com/dm.svg" },
  { label: "Dominican Republic (+1-809)", value: "+1-809", src: "https://flagcdn.com/do.svg" },
  { label: "Ecuador (+593)", value: "+593", src: "https://flagcdn.com/ec.svg" },
  { label: "Egypt (+20)", value: "+20", src: "https://flagcdn.com/eg.svg" },
  { label: "El Salvador (+503)", value: "+503", src: "https://flagcdn.com/sv.svg" },
  { label: "Equatorial Guinea (+240)", value: "+240", src: "https://flagcdn.com/gq.svg" },
  { label: "Eritrea (+291)", value: "+291", src: "https://flagcdn.com/er.svg" },
  { label: "Estonia (+372)", value: "+372", src: "https://flagcdn.com/ee.svg" },
  { label: "Ethiopia (+251)", value: "+251", src: "https://flagcdn.com/et.svg" },
  { label: "Falkland Islands (Malvinas) (+500)", value: "+500", src: "https://flagcdn.com/fk.svg" },
  { label: "Faroe Islands (+298)", value: "+298", src: "https://flagcdn.com/fo.svg" },
  { label: "Fiji (+679)", value: "+679", src: "https://flagcdn.com/fj.svg" },
  { label: "Finland (+358)", value: "+358", src: "https://flagcdn.com/fi.svg" },
  { label: "France (+33)", value: "+33", src: "https://flagcdn.com/fr.svg" },
  { label: "French Guiana (+594)", value: "+594", src: "https://flagcdn.com/gf.svg" },
  { label: "French Polynesia (+689)", value: "+689", src: "https://flagcdn.com/pf.svg" },
  { label: "French Southern Territories (+262)", value: "+262", src: "https://flagcdn.com/tf.svg" },
  { label: "Gabon (+241)", value: "+241", src: "https://flagcdn.com/ga.svg" },
  { label: "Gambia (+220)", value: "+220", src: "https://flagcdn.com/gm.svg" },
  { label: "Georgia (+995)", value: "+995", src: "https://flagcdn.com/ge.svg" },
  { label: "Germany (+49)", value: "+49", src: "https://flagcdn.com/de.svg" },
  { label: "Ghana (+233)", value: "+233", src: "https://flagcdn.com/gh.svg" },
  { label: "Gibraltar (+350)", value: "+350", src: "https://flagcdn.com/gi.svg" },
  { label: "Greece (+30)", value: "+30", src: "https://flagcdn.com/gr.svg" },
  { label: "Greenland (+299)", value: "+299", src: "https://flagcdn.com/gl.svg" },
  { label: "Grenada (+1-473)", value: "+1-473", src: "https://flagcdn.com/gd.svg" },
  { label: "Guadeloupe (+590)", value: "+590", src: "https://flagcdn.com/gp.svg" },
  { label: "Guam (+1-671)", value: "+1-671", src: "https://flagcdn.com/gu.svg" },
  { label: "Guatemala (+502)", value: "+502", src: "https://flagcdn.com/gt.svg" },
  { label: "Guernsey (+44-1481)", value: "+44-1481", src: "https://flagcdn.com/gg.svg" },
  { label: "Guinea (+224)", value: "+224", src: "https://flagcdn.com/gn.svg" },
  { label: "Guinea-Bissau (+245)", value: "+245", src: "https://flagcdn.com/gw.svg" },
  { label: "Guyana (+592)", value: "+592", src: "https://flagcdn.com/gy.svg" },
  { label: "Haiti (+509)", value: "+509", src: "https://flagcdn.com/ht.svg" },
  { label: "Heard Island and Mcdonald Islands (+672)", value: "+672", src: "https://flagcdn.com/hm.svg" },
  { label: "Holy See (Vatican City State) (+379)", value: "+379", src: "https://flagcdn.com/va.svg" },
  { label: "Honduras (+504)", value: "+504", src: "https://flagcdn.com/hn.svg" },
  { label: "Hong Kong (+852)", value: "+852", src: "https://flagcdn.com/hk.svg" },
  { label: "Hungary (+36)", value: "+36", src: "https://flagcdn.com/hu.svg" },
  { label: "Iceland (+354)", value: "+354", src: "https://flagcdn.com/is.svg" },
  { label: "India (+91)", value: "+91", src: "https://flagcdn.com/in.svg" },
  { label: "Indonesia (+62)", value: "+62", src: "https://flagcdn.com/id.svg" },
  { label: "Iran, Islamic Republic Of (+98)", value: "+98", src: "https://flagcdn.com/ir.svg" },
  { label: "Iraq (+964)", value: "+964", src: "https://flagcdn.com/iq.svg" },
  { label: "Ireland (+353)", value: "+353", src: "https://flagcdn.com/ie.svg" },
  { label: "Isle of Man (+44-1624)", value: "+44-1624", src: "https://flagcdn.com/im.svg" },
  { label: "Israel (+972)", value: "+972", src: "https://flagcdn.com/il.svg" },
  { label: "Italy (+39)", value: "+39", src: "https://flagcdn.com/it.svg" },
  { label: "Jamaica (+1-876)", value: "+1-876", src: "https://flagcdn.com/jm.svg" },
  { label: "Japan (+81)", value: "+81", src: "https://flagcdn.com/jp.svg" },
  { label: "Jersey (+44-1534)", value: "+44-1534", src: "https://flagcdn.com/je.svg" },
  { label: "Jordan (+962)", value: "+962", src: "https://flagcdn.com/jo.svg" },
  { label: "Kazakhstan (+7)", value: "+7", src: "https://flagcdn.com/kz.svg" },
  { label: "Kenya (+254)", value: "+254", src: "https://flagcdn.com/ke.svg" },
  { label: "Kiribati (+686)", value: "+686", src: "https://flagcdn.com/ki.svg" },
  { label: "Korea, Democratic People's Republic of (+850)", value: "+850", src: "https://flagcdn.com/kp.svg" },
  { label: "Korea, Republic of (+82)", value: "+82", src: "https://flagcdn.com/kr.svg" },
  { label: "Kuwait (+965)", value: "+965", src: "https://flagcdn.com/kw.svg" },
  { label: "Kyrgyzstan (+996)", value: "+996", src: "https://flagcdn.com/kg.svg" },
  { label: "Lao People's Democratic Republic (+856)", value: "+856", src: "https://flagcdn.com/la.svg" },
  { label: "Latvia (+371)", value: "+371", src: "https://flagcdn.com/lv.svg" },
  { label: "Lebanon (+961)", value: "+961", src: "https://flagcdn.com/lb.svg" },
  { label: "Lesotho (+266)", value: "+266", src: "https://flagcdn.com/ls.svg" },
  { label: "Liberia (+231)", value: "+231", src: "https://flagcdn.com/lr.svg" },
  { label: "Libya (+218)", value: "+218", src: "https://flagcdn.com/ly.svg" },
  { label: "Liechtenstein (+423)", value: "+423", src: "https://flagcdn.com/li.svg" },
  { label: "Lithuania (+370)", value: "+370", src: "https://flagcdn.com/lt.svg" },
  { label: "Luxembourg (+352)", value: "+352", src: "https://flagcdn.com/lu.svg" },
  { label: "Macao (+853)", value: "+853", src: "https://flagcdn.com/mo.svg" },
  { label: "Macedonia, The Former Yugoslav Republic of (+389)", value: "+389", src: "https://flagcdn.com/mk.svg" },
  { label: "Madagascar (+261)", value: "+261", src: "https://flagcdn.com/mg.svg" },
  { label: "Malawi (+265)", value: "+265", src: "https://flagcdn.com/mw.svg" },
  { label: "Malaysia (+60)", value: "+60", src: "https://flagcdn.com/my.svg" },
  { label: "Maldives (+960)", value: "+960", src: "https://flagcdn.com/mv.svg" },
  { label: "Mali (+223)", value: "+223", src: "https://flagcdn.com/ml.svg" },
  { label: "Malta (+356)", value: "+356", src: "https://flagcdn.com/mt.svg" },
  { label: "Marshall Islands (+692)", value: "+692", src: "https://flagcdn.com/mh.svg" },
  { label: "Martinique (+596)", value: "+596", src: "https://flagcdn.com/mq.svg" },
  { label: "Mauritania (+222)", value: "+222", src: "https://flagcdn.com/mr.svg" },
  { label: "Mauritius (+230)", value: "+230", src: "https://flagcdn.com/mu.svg" },
  { label: "Mayotte (+262)", value: "+262", src: "https://flagcdn.com/yt.svg" },
  { label: "Mexico (+52)", value: "+52", src: "https://flagcdn.com/mx.svg" },
  { label: "Micronesia, Federated States of (+691)", value: "+691", src: "https://flagcdn.com/fm.svg" },
  { label: "Moldova, Republic of (+373)", value: "+373", src: "https://flagcdn.com/md.svg" },
  { label: "Monaco (+377)", value: "+377", src: "https://flagcdn.com/mc.svg" },
  { label: "Mongolia (+976)", value: "+976", src: "https://flagcdn.com/mn.svg" },
  { label: "Montenegro (+382)", value: "+382", src: "https://flagcdn.com/me.svg" },
  { label: "Montserrat (+1-664)", value: "+1-664", src: "https://flagcdn.com/ms.svg" },
  { label: "Morocco (+212)", value: "+212", src: "https://flagcdn.com/ma.svg" },
  { label: "Mozambique (+258)", value: "+258", src: "https://flagcdn.com/mz.svg" },
  { label: "Myanmar (+95)", value: "+95", src: "https://flagcdn.com/mm.svg" },
  { label: "Namibia (+264)", value: "+264", src: "https://flagcdn.com/na.svg" },
  { label: "Nauru (+674)", value: "+674", src: "https://flagcdn.com/nr.svg" },
  { label: "Nepal (+977)", value: "+977", src: "https://flagcdn.com/np.svg" },
  { label: "Netherlands (+31)", value: "+31", src: "https://flagcdn.com/nl.svg" },
  { label: "Netherlands Antilles (+599)", value: "+599", src: "https://flagcdn.com/an.svg" },
  { label: "New Caledonia (+687)", value: "+687", src: "https://flagcdn.com/nc.svg" },
  { label: "New Zealand (+64)", value: "+64", src: "https://flagcdn.com/nz.svg" },
  { label: "Nicaragua (+505)", value: "+505", src: "https://flagcdn.com/ni.svg" },
  { label: "Niger (+227)", value: "+227", src: "https://flagcdn.com/ne.svg" },
  { label: "Nigeria (+234)", value: "+234", src: "https://flagcdn.com/ng.svg" },
  { label: "Niue (+683)", value: "+683", src: "https://flagcdn.com/nu.svg" },
  { label: "Norfolk Island (+672)", value: "+672", src: "https://flagcdn.com/nf.svg" },
  { label: "Northern Mariana Islands (+1-670)", value: "+1-670", src: "https://flagcdn.com/mp.svg" },
  { label: "Norway (+47)", value: "+47", src: "https://flagcdn.com/no.svg" },
  { label: "Oman (+968)", value: "+968", src: "https://flagcdn.com/om.svg" },
  { label: "Pakistan (+92)", value: "+92", src: "https://flagcdn.com/pk.svg" },
  { label: "Palau (+680)", value: "+680", src: "https://flagcdn.com/pw.svg" },
  { label: "Palestinian Territory, Occupied (+970)", value: "+970", src: "https://flagcdn.com/ps.svg" },
  { label: "Panama (+507)", value: "+507", src: "https://flagcdn.com/pa.svg" },
  { label: "Papua New Guinea (+675)", value: "+675", src: "https://flagcdn.com/pg.svg" },
  { label: "Paraguay (+595)", value: "+595", src: "https://flagcdn.com/py.svg" },
  { label: "Peru (+51)", value: "+51", src: "https://flagcdn.com/pe.svg" },
  { label: "Philippines (+63)", value: "+63", src: "https://flagcdn.com/ph.svg" },
  { label: "Pitcairn (+870)", value: "+870", src: "https://flagcdn.com/pn.svg" },
  { label: "Poland (+48)", value: "+48", src: "https://flagcdn.com/pl.svg" },
  { label: "Portugal (+351)", value: "+351", src: "https://flagcdn.com/pt.svg" },
  { label: "Puerto Rico (+1-787)", value: "+1-787", src: "https://flagcdn.com/pr.svg" },
  { label: "Qatar (+974)", value: "+974", src: "https://flagcdn.com/qa.svg" },
  { label: "Réunion (+262)", value: "+262", src: "https://flagcdn.com/re.svg" },
  { label: "Romania (+40)", value: "+40", src: "https://flagcdn.com/ro.svg" },
  { label: "Russian Federation (+7)", value: "+7", src: "https://flagcdn.com/ru.svg" },
  { label: "Rwanda (+250)", value: "+250", src: "https://flagcdn.com/rw.svg" },
  { label: "Saint Helena (+290)", value: "+290", src: "https://flagcdn.com/sh.svg" },
  { label: "Saint Kitts and Nevis (+1-869)", value: "+1-869", src: "https://flagcdn.com/kn.svg" },
  { label: "Saint Lucia (+1-758)", value: "+1-758", src: "https://flagcdn.com/lc.svg" },
  { label: "Saint Pierre and Miquelon (+508)", value: "+508", src: "https://flagcdn.com/pm.svg" },
  { label: "Saint Vincent and the Grenadines (+1-784)", value: "+1-784", src: "https://flagcdn.com/vc.svg" },
  { label: "Samoa (+685)", value: "+685", src: "https://flagcdn.com/ws.svg" },
  { label: "San Marino (+378)", value: "+378", src: "https://flagcdn.com/sm.svg" },
  { label: "Sao Tome and Principe (+239)", value: "+239", src: "https://flagcdn.com/st.svg" },
  { label: "Saudi Arabia (+966)", value: "+966", src: "https://flagcdn.com/sa.svg" },
  { label: "Senegal (+221)", value: "+221", src: "https://flagcdn.com/sn.svg" },
  { label: "Serbia (+381)", value: "+381", src: "https://flagcdn.com/rs.svg" },
  { label: "Seychelles (+248)", value: "+248", src: "https://flagcdn.com/sc.svg" },
  { label: "Sierra Leone (+232)", value: "+232", src: "https://flagcdn.com/sl.svg" },
  { label: "Singapore (+65)", value: "+65", src: "https://flagcdn.com/sg.svg" },
  { label: "Slovakia (+421)", value: "+421", src: "https://flagcdn.com/sk.svg" },
  { label: "Slovenia (+386)", value: "+386", src: "https://flagcdn.com/si.svg" },
  { label: "Solomon Islands (+677)", value: "+677", src: "https://flagcdn.com/sb.svg" },
  { label: "Somalia (+252)", value: "+252", src: "https://flagcdn.com/so.svg" },
  { label: "South Africa (+27)", value: "+27", src: "https://flagcdn.com/za.svg" },
  { label: "South Georgia and the South Sandwich Islands (+500)", value: "+500", src: "https://flagcdn.com/gs.svg" },
  { label: "Spain (+34)", value: "+34", src: "https://flagcdn.com/es.svg" },
  { label: "Sri Lanka (+94)", value: "+94", src: "https://flagcdn.com/lk.svg" },
  { label: "Sudan (+249)", value: "+249", src: "https://flagcdn.com/sd.svg" },
  { label: "Suriname (+597)", value: "+597", src: "https://flagcdn.com/sr.svg" },
  { label: "Svalbard and Jan Mayen (+47)", value: "+47", src: "https://flagcdn.com/sj.svg" },
  { label: "Swaziland (+268)", value: "+268", src: "https://flagcdn.com/sz.svg" },
  { label: "Sweden (+46)", value: "+46", src: "https://flagcdn.com/se.svg" },
  { label: "Switzerland (+41)", value: "+41", src: "https://flagcdn.com/ch.svg" },
  { label: "Syrian Arab Republic (+963)", value: "+963", src: "https://flagcdn.com/sy.svg" },
  { label: "Taiwan, Province of China (+886)", value: "+886", src: "https://flagcdn.com/tw.svg" },
  { label: "Tajikistan (+992)", value: "+992", src: "https://flagcdn.com/tj.svg" },
  { label: "Tanzania (+255)", value: "+255", src: "https://flagcdn.com/tz.svg" },
  { label: "Thailand (+66)", value: "+66", src: "https://flagcdn.com/th.svg" },
  { label: "Timor-Leste (+670)", value: "+670", src: "https://flagcdn.com/tl.svg" },
  { label: "Togo (+228)", value: "+228", src: "https://flagcdn.com/tg.svg" },
  { label: "Tokelau (+690)", value: "+690", src: "https://flagcdn.com/tk.svg" },
  { label: "Tonga (+676)", value: "+676", src: "https://flagcdn.com/to.svg" },
  { label: "Trinidad and Tobago (+1-868)", value: "+1-868", src: "https://flagcdn.com/tt.svg" },
  { label: "Tunisia (+216)", value: "+216", src: "https://flagcdn.com/tn.svg" },
  { label: "Turkey (+90)", value: "+90", src: "https://flagcdn.com/tr.svg" },
  { label: "Turkmenistan (+993)", value: "+993", src: "https://flagcdn.com/tm.svg" },
  { label: "Turks and Caicos Islands (+1-649)", value: "+1-649", src: "https://flagcdn.com/tc.svg" },
  { label: "Tuvalu (+688)", value: "+688", src: "https://flagcdn.com/tv.svg" },
  { label: "Uganda (+256)", value: "+256", src: "https://flagcdn.com/ug.svg" },
  { label: "Ukraine (+380)", value: "+380", src: "https://flagcdn.com/ua.svg" },
  { label: "United Arab Emirates (+971)", value: "+971", src: "https://flagcdn.com/ae.svg" },
  { label: "United Kingdom (+44)", value: "+44", src: "https://flagcdn.com/gb.svg" },
  { label: "United States (+1)", value: "+1", src: "https://flagcdn.com/us.svg" },
  { label: "Uruguay (+598)", value: "+598", src: "https://flagcdn.com/uy.svg" },
  { label: "Uzbekistan (+998)", value: "+998", src: "https://flagcdn.com/uz.svg" },
  { label: "Vanuatu (+678)", value: "+678", src: "https://flagcdn.com/vu.svg" },
  { label: "Venezuela (+58)", value: "+58", src: "https://flagcdn.com/ve.svg" },
  { label: "Viet Nam (+84)", value: "+84", src: "https://flagcdn.com/vn.svg" },
  { label: "Virgin Islands, British (+1-284)", value: "+1-284", src: "https://flagcdn.com/vg.svg" },
  { label: "Virgin Islands, U.S. (+1-340)", value: "+1-340", src: "https://flagcdn.com/vi.svg" },
  { label: "Wallis and Futuna (+681)", value: "+681", src: "https://flagcdn.com/wf.svg" },
  { label: "Western Sahara (+212)", value: "+212", src: "https://flagcdn.com/eh.svg" },
  { label: "Yemen (+967)", value: "+967", src: "https://flagcdn.com/ye.svg" },
  { label: "Zambia (+260)", value: "+260", src: "https://flagcdn.com/zm.svg" },
  { label: "Zimbabwe (+263)", value: "+263", src: "https://flagcdn.com/zw.svg" },
];
